### ISSUE TITLE
Allow AE2/RS storage bus output

### ISSUE THREAD

**Issue by maxhenkes** [GirafiStudios/Impractical-Storage#10]
Not sure it's intended that way, but AE2 storage bus and apparently rs ones can input into the controller, but can't output.

Would be amazing as an earlygame storage option combined with something like AE and restricting storage disks. Thank you for making this mod! :)

**Comment by Mattabase** [comment]
Put the Storage Controller in "Messy Mode" and fill the controller all the way. You can pull stuff out, it is a little odd. 

If you put the Storage controller to a 1x1x1 then you can put and pull out as well. 

https://goo.gl/m4B7Eq

**Comment by Mattabase** [comment]
https://goo.gl/m4B7Eq

**Comment by dmillerw** [comment]
Weird inventory interaction? Doesn't properly see the full availability? To be investigated
