### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by Mattabase** [GirafiStudios/Impractical-Storage#11]
https://goo.gl/TdozTZ

FPS is hit REALLY hard while looking at a really big Storage Setup. 

https://goo.gl/wrP61Q

Even this drops me from 400+ FPS to 200 when I have the controllers down.

**Comment by dmillerw** [comment]
Todo, cache more things. Probably a rogue method call

**Comment by dmillerw** [comment]
Should be fixed with 5bfc020b7e48f08b196c315acc118069f899e555

**Comment by dmillerw** [comment]
Closed, assuming fixed. Comment if not

**Comment by Mattabase** [comment]
Sorry on the slow response. It is indeed Fixed.
