### ISSUE TITLE
Interaction with Embers and Hopperducts

### ISSUE THREAD

**Issue by SeriousCreeper** [GirafiStudios/Impractical-Storage#12]
Heya,

first of all, i'm super in love with this mod, always meant to have a storage system back in vanilla where i just place all my ore blocks rather than putting them into a chest, and this mod makes this so much better :D 

However, i just tried to pump items into (and out of) the controller using both Embers item pipes and pumps, and also Hopperducts. Neither of them seem to work with the controller, it doesn't seem to insert them properly. 

I replaced the controller with a chest to double check and sure enough, the items get pumped into the chest. 
Vanilla hoppers work fine however. 

Is this an issue with those mentioned mods, or with impractical storage? 

Using latest version of everything. Let me know if i can provide any additional information that would be helpful!

Thanks,
SC

**Comment by dmillerw** [comment]
There's definitely an issue with mod interaction I have to track down. Appreciate the report!
