### ISSUE TITLE
Item icon's go black with shaders

### ISSUE THREAD

**Issue by ghost** [GirafiStudios/Impractical-Storage#13]
http://i.imgur.com/U50xUNe.jpg

**Comment by dmillerw** [comment]
Probably lighting issue, investigate

**Comment by dmillerw** [comment]
This may be fixed with 5bfc020b7e48f08b196c315acc118069f899e555, will require further testing

**Comment by dmillerw** [comment]
Test with version 1.2.1 and see if the issue persists

**Comment by dmillerw** [comment]
Closing, assuming fixed
