### ISSUE TITLE
No way to get items back out

### ISSUE THREAD

**Issue by Zygus42** [GirafiStudios/Impractical-Storage#17]
Just tried new version 1.10.2 v1.2.  Right clicking on the controller brings up the interface to see, size the boundaries & how the items are stacked.  Piping items in via a Hopper works fine, but I can't get the items back out.  Tried a pick and an axe on the stored items, and neither works.  Is there meant to be an inventory when right-clicking on the controller, because there isn't ?

**Comment by dmillerw** [comment]
You can pipe them back out, or shift-right-click on the blocks in-world to retrieve them. It's explained in the MCF post

**Comment by dmillerw** [comment]
> So how do you interact with the block? Same way you interact with any other inventory. Blocks and items can be piped in and out the same way you'd interact with a chest, using whatever means you desire. Not only that, but blocks in the world can be shift-right-clicked to retrieve them, and any blocks placed inside the controller's zone will be added to the inventory
