### ISSUE TITLE
63 Is Max

### ISSUE THREAD

**Issue by Mattabase** [GirafiStudios/Impractical-Storage#19]
https://goo.gl/sr0BKz

I can not set the number to 64

It also lagged REALLY hard when I put the last number to 63

https://goo.gl/NsUqYr

Also got this crash when typing in the second box.

**Comment by dmillerw** [comment]
64 is the default maximum, but that can be changed in the actual config file. Mainly there for server owners

As for everything else, unable to reproduce. The lag is simply to be expected for a boundary of that size, unfortunately
