### ISSUE TITLE
Crash and Dupe Bug

### ISSUE THREAD

**Issue by Mattabase** [GirafiStudios/Impractical-Storage#20]
https://goo.gl/5yn6V9

I changed the sorting type while it was filling - from Rows to Messy.

When I loaded the game again, all the blocks had dropped on the ground but the blocks still existed in the controller area. I was then able to shift click the remaining blocks infinitely

**Comment by dmillerw** [comment]
_should_ be fixed by 83114740900ac423f534aa78d300cd9829a6190d
