### ISSUE TITLE
Shift Click and Right Click bug

### ISSUE THREAD

**Issue by Terpo** [GirafiStudios/Impractical-Storage#21]
v 1.2.1

Take a Refined Storage System. Put in a stack of items. Try to extract them through the Grid with a right click or a shift left click. It always gives you one item, but removes the whole stack.

**Comment by dmillerw** [comment]
Can't seem to reproduce, which MC version are you running?

**Comment by Terpo** [comment]
1.11.2 with forge 2230
refinedstorage-1.4
ImpracticalStorage-1.2.1-MC1.11.2

current modlist: https://gist.github.com/Terpo/da471f14ba90dab907d591c2f98195f9

https://youtu.be/6ilc5yf_NiI
shift click
left click
right click

could be a cross mod problem^^
