### ISSUE TITLE
[Feature Request] Moveable bounding area

### ISSUE THREAD

**Issue by DreamingLamb** [GirafiStudios/Impractical-Storage#24]
Just wondering if it would be possible to add the option to love the bounding area of the Storage Controller.  This could allow two or more Storage Controllers to be placed next to each other but not have their areas overlap.

For example, placing two controllers at x10 and x11 and having the bounding areas run from x1-x10 and x11-x20

**Comment by DreamingLamb** [comment]
Love was meant to be move, I can't see an edit option on my phone.

**Comment by dmillerw** [comment]
Yes, is planned

**Comment by dmillerw** [comment]
Closed, dup of #22
