### ISSUE TITLE
weird interaction with refined storage

### ISSUE THREAD

**Issue by AndreiTS** [GirafiStudios/Impractical-Storage#27]
64 stone
![2017-03-30_13 24 23](https://cloud.githubusercontent.com/assets/13489837/24515022/a31ef170-154c-11e7-8098-7bad407bf6c5.png)
put on refined storage with a external storage attached to the controller shows 68
![2017-03-30_13 24 25](https://cloud.githubusercontent.com/assets/13489837/24515023/a325c8d8-154c-11e7-9a1c-f6b539617ee4.png)

**Comment by AndreiTS** [comment]
cause: setup, in the first one, it shows 64, but in the second setup it shows 68
![2017-03-30_13 30 32](https://cloud.githubusercontent.com/assets/13489837/24515152/163825c8-154d-11e7-8dec-457313d618c8.png)
![2017-03-30_13 30 37](https://cloud.githubusercontent.com/assets/13489837/24515153/1637ea72-154d-11e7-8f4c-f8ae0e1c01f6.png)

![2017-03-30_13 31 36](https://cloud.githubusercontent.com/assets/13489837/24515209/3bb56040-154d-11e7-98cd-d957f8604830.png)
![2017-03-30_13 31 40](https://cloud.githubusercontent.com/assets/13489837/24515211/3bdea266-154d-11e7-8c1f-969d3bffddc3.png)

**Comment by dmillerw** [comment]
I swear, every time I fix a bug with refined storage, two more appear. What Mc version?

**Comment by AndreiTS** [comment]
1.10.2
refined storage: 1.2.24

**Comment by dmillerw** [comment]
Looks like you have two External Storage things connected to the controller, one via an interface? RS will always look like there's more in an inventory than there is if you have one than one External Storage connector

**Comment by dmillerw** [comment]
Nvm, did some more testing, definitely a bug.

**Comment by dmillerw** [comment]
Investigating, closing in favor of #28
