### ISSUE TITLE
crash on GUI

### ISSUE THREAD

**Issue by Zygus42** [GirafiStudios/Impractical-Storage#31]
1.10.2 v1.3.1
Crash when adjusting sort method on GUI:
[crash-2017-04-03_12.27.25-server.txt](https://github.com/dmillerw/Impractical-Storage/files/888990/crash-2017-04-03_12.27.25-server.txt)

**Comment by dmillerw** [comment]
Fixed 0c96ace6d3b3531e609f5aa92985fbca7eabf626
