### ISSUE TITLE
Crash when changing  boundaries on a storage zone.

### ISSUE THREAD

**Issue by LWnellA** [GirafiStudios/Impractical-Storage#32]
[crash-2017-04-03_17.36.56-server.txt](https://github.com/dmillerw/Impractical-Storage/files/889403/crash-2017-04-03_17.36.56-server.txt)

**Comment by cdbbnnyCode** [comment]
I had the same error when changing the sorting method. Seems to be because the inventory of the controller is **null**.

**Comment by dmillerw** [comment]
Fixed 0c96ace6d3b3531e609f5aa92985fbca7eabf626
