### ISSUE TITLE
WAILA/Hwyla/TOP don't report the actual block stored

### ISSUE THREAD

**Issue by Claycorp** [GirafiStudios/Impractical-Storage#38]
If possible it would be great when you look at a stored/storage block mods like Waila/Hwyla/TOP and any other acronymed mods for looking at stuff would display the name of the block/items stored in that spot rather than the unlocalized tile name.

![image](https://cloud.githubusercontent.com/assets/3961359/24824177/898a500c-1bcc-11e7-8fd0-48bf32bb5d0e.png)

**Comment by dmillerw** [comment]
Will look in to, for sure

**Comment by Claycorp** [comment]
Dam fast! :+1:

**Comment by dmillerw** [comment]
You caught me in the middle of bug fixing mode 🎉
