### ISSUE TITLE
[1.11.2] Crash with acacia planks and the itemizer

### ISSUE THREAD

**Issue by SeriousCreeper** [GirafiStudios/Impractical-Storage#40]
Crash-log: https://pastebin.com/41FeBQBF 

I build a setup of a dispenser placing blocks on the blockvator thing, that runs infront of a gravity block, and then falls down next to the itemizer (and the item that drops gets picked up by a hopper and pushed into a storage controller). 

Also i just wanna say how freaking awesome those new blocks are, love it.

**Comment by dmillerw** [comment]
Fixing now

Just a heads up, if you drop a block via the Gravity Inducer directly into a Controller's boundaries, it'll add it automatically to the inventory ;)

**Comment by SeriousCreeper** [comment]
Oh derp, haha even better! Thanks
