### ISSUE TITLE
Way to insert items other than with hoppers/pipes.

### ISSUE THREAD

**Issue by Claycorp** [GirafiStudios/Impractical-Storage#42]
Currently there is no other way to insert items that are not place-able other than hoppers. (that I know of or could find info about) I think this would be a great mod to use as a total storage replacement in a pack but the fact you can't place unplaceable stuff in it makes it a challenge to work.

You might have plans for this already for all I know anyway :P

**Comment by dmillerw** [comment]
Crates will eventually be required to store items, and they'll be interacted with directly, similar to barrels. So, yes, planned
