### ISSUE TITLE
[1.11.2] Odd render issue between ImpStor and Botania

### ISSUE THREAD

**Issue by starg09** [GirafiStudios/Impractical-Storage#43]
Versions used:

* Forge 2279 (MC 1.11.2)
* Impractical Storage 1.4.1
* ~~Baubles 1.4.3~~
* Botania r1.9-342

What happens is that, when you're on either Spectator Mode, or you press the F1 key on any mode, the renderer bugs out and you lose all colors. Not sure whether this is on your side or on Baubles' though. Issue only happens when both mods are present...

**Comment by dmillerw** [comment]
I'm gonna say it's on Baubles end, since I don't actually mess with rendering really at all. I'll take a look though

**Comment by dmillerw** [comment]
Just tested it and wasn't able to reproduce the issue

**Comment by starg09** [comment]
Oh, excuse me! I crossed up two things. It was Botania the one that caused the issue, not Baubles... I just tested both, then removed botania and it solved itself. Whoops! 😛 

So yeah, it would be ImpStor and Botania, Baubles has no problem (but it's a dep for Botania, that's why it was added)

**Comment by dmillerw** [comment]
That would make more sense. Why Botania would mess up with ImpStorage installed though is beyond me, but I'll take a look

**Comment by ghost** [comment]
I found the same issue on 1.12 with Imp Storage and Silent's gems. After a significant amount of testing to find out what was causing it I narrowed it down to loading minecraft with just Those two mods (and silent lib) with all default minecraft and mod configs.

**Comment by ghost** [comment]
updating this again. Same issue with astral sorcery and in that specific case it also messes with the visual effect from astral sorcery cave illuminators and teleporters

**Comment by marbleflower** [comment]
I have the same issue using forge 1.10.2-12.18.3.2511 using Botania r1.9-341 with ImpracticalStorage-1.4.3-MC1.10.2. I made a video showing the render glitch. [link](https://www.youtube.com/watch?v=OiUZ92TlQsE)
