### ISSUE TITLE
Changing Boundaries Has No Effect & BetterFoliage Crash

### ISSUE THREAD

**Issue by Rory-Lambert** [GirafiStudios/Impractical-Storage#44]
Love the mod! Been loving all the new updates!
Anyway, for whatever reason, on my custom modpack I am not able to change any of the settings for the storage controller. The preview does not change as intended, and when I tried to change the sort mode whilst items were being piped in (to test if it was just a visual glitch), the game crashed (logs attached). 

Any time I exit the GUI, opening it again defaults to 8,8,8 ; 0,0,0 rows as default. I'd love to be able to get this to work, but I cant work out from the logs what is causing this to fail :/

[crash-2017-04-11_21.59.23-client.txt](https://github.com/dmillerw/Impractical-Storage/files/914684/crash-2017-04-11_21.59.23-client.txt)

Thanks!

**Comment by calloatti** [comment]
To make the change stick, click on the textbox itself and type a number , press enter

**Comment by dmillerw** [comment]
If you change the bounds by clicking on the up and down buttons, does that stick?

**Comment by RL-AFM** [comment]
When updating the bounds on a client, neither key or mouse entry has any effect. Clicking show boundaries toggles the default 8x8x8 box, but no changes are displayed on this box. Exiting the GUI removes the boundary preview, and any changes made do not stick. Just in case, what is the recommended exit GUI button? I play left handed so my keybinds are all whack. It appears that this does not close the Gui on close inventory, so I've had to use Esc. 

Note that when running the same modpack on a local machine the previewing works, and Esc'ing out of the GUI in place, in this case, the functionality seems to work as intended for a few blocks, before crashing client.

Cheers

**Comment by Rory-Lambert** [comment]
When updating the bounds on a client, neither key or mouse entry has any effect. Clicking show boundaries toggles the default 8x8x8 box, but no changes are displayed on this box. Exiting the GUI removes the boundary preview, and any changes made do not stick. Just in case, what is the recommended exit GUI button? I play left handed so my keybinds are all whack. It appears that this does not close the Gui on close inventory, so I've had to use Esc. 

Note that when running the same modpack on a local machine the previewing works, and Esc'ing out of the GUI in place, in this case, the functionality seems to work as intended for a few blocks, before crashing client.

Cheers

**Comment by dmillerw** [comment]
@lookbehindyoo 
The issue regarding changes not sticking when playing on servers has been fixed. Could you do me a favor and see if there's a specific block that's being piped in that's causing the crash?

**Comment by Rory-Lambert** [comment]
great news. just updating now and will try it out. As for the particular blocks, I would imagine it was some type of stone from underground biomes constructs, since these replace cobblestone, and are thus the most numerous blocks (therefore the ones I would test with in survival). I'll check and get back to you though
