### ISSUE TITLE
Crash after updating mod

### ISSUE THREAD

**Issue by LWnellA** [GirafiStudios/Impractical-Storage#46]
I updated the mod and afterwards, I'm constantly getting a crash when trying to load the world. New worlds seems to load fine though.
[crash-2017-04-12_19.22.40-client.txt](https://github.com/dmillerw/Impractical-Storage/files/916187/crash-2017-04-12_19.22.40-client.txt)

**Comment by dmillerw** [comment]
Same crash as #44
