### ISSUE TITLE
Client crash on items rendering inside the storage area

### ISSUE THREAD

**Issue by Rory-Lambert** [GirafiStudios/Impractical-Storage#50]
Continuation of #44. The recent update fixed the server not offsetting boundaries correctly, but the crashing problem persists. FYI it looks like updating the x coord in the GUI only re-draws the boundary every other block. i.e. 2,4,6 wide settings remain at 1,3,5 etc. 

Anyway, here are two consecutive crash reports regarding the title issue. 
[crash-2017-04-22_17.34.26-client.txt](https://github.com/dmillerw/Impractical-Storage/files/949134/crash-2017-04-22_17.34.26-client.txt)
[crash-2017-04-22_17.42.34-client.txt](https://github.com/dmillerw/Impractical-Storage/files/949133/crash-2017-04-22_17.42.34-client.txt)

These crashes occurred when logs and planks respectively were being placed into the storage area via a hopper. When I restarted the client, the server was fine, and all items had placed correctly. 

Cheers

Edit: A few more, trying without optifine, foamfix and betterfps. I think its the same error each time regardless.
[crash-2017-04-22_18.06.00-client.txt](https://github.com/dmillerw/Impractical-Storage/files/949143/crash-2017-04-22_18.06.00-client.txt)
[crash-2017-04-22_18.12.52-client.txt](https://github.com/dmillerw/Impractical-Storage/files/949144/crash-2017-04-22_18.12.52-client.txt)
[crash-2017-04-22_18.18.25-client.txt](https://github.com/dmillerw/Impractical-Storage/files/949145/crash-2017-04-22_18.18.25-client.txt)
[crash-2017-04-22_17.57.50-client.txt](https://github.com/dmillerw/Impractical-Storage/files/949142/crash-2017-04-22_17.57.50-client.txt)

**Comment by dmillerw** [comment]
@lookbehindyoo could you try reproducing this with v1.4.3?

**Comment by Rory-Lambert** [comment]
Tried with v1.4.3 last night and appears to be working as intended. Thanks for the fix, really looking forward to playing around with this! :)
