### ISSUE TITLE
[bug] not working at all

### ISSUE THREAD

**Issue by Zygus42** [GirafiStudios/Impractical-Storage#6]
Just tried 1.10.2 v1.1, and placing the controller in the world draws some lines forming a cube, but right-clicking on it with items, blocks or bare hands does nothing at all, and left-clicking (in survival) destroys the controller block.

**Comment by Terpo** [comment]
Yeah, seems missing tool and hardness for breaking.
Item Input works with a hopper.
Output works also with a hopper.
Refined Storage external storage can insert but can't take out atm.

**Comment by dmillerw** [comment]
That's my bad, will be fixed asap

I'll have to test with a wider array of other mods, for sure. 

Appreciate the report.

**Comment by dmillerw** [comment]
Tracking via issue #15
