### ISSUE TITLE
Changing Bounding Size of Full Block

### ISSUE THREAD

**Issue by Mattabase** [GirafiStudios/Impractical-Storage#7]
https://goo.gl/DwHV1G

Happened when I changed the bounds of the Storage Controller while it was full. 

Not able to get it to happen reliably though.

**Comment by dmillerw** [comment]
I kind of want to say this is an MC issue. I can't track down the cause just yet

**Comment by Flabort** [comment]
I wonder... did you SHRINK the full storage, or how did you do it?

**Comment by dmillerw** [comment]
_should_ be fixed by 83114740900ac423f534aa78d300cd9829a6190d
